modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
    modId = "jamd"
    version = "${mod_version}"
    displayName = "Just Another Mining Dimension"
    logoFile = "assets/jamd/logo.png"
    credits = ""
    authors = "UnRealDinnerbone"
    description = "Adds a mining dimension to the game."
[[dependencies.jamd]]
    modId = "neoforge"
    required = true
    versionRange = "[1.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.jamd]]
    modId = "minecraft"
    required = true
    versionRange = "[${minecraft_version}]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.jamd]]
    modId = "trenzalore"
    required = true
    versionRange = "[${trenzalore_version},)"
    ordering = "NONE"
    side = "BOTH"